#!/bin/bash
echo "Building BeagleBone Application..."
g++ -std=c++17 ../../../Sources/RAINBOWCOLORS.cpp ../../../Sources/SYSFILEACCESS.cpp ../../../Sources/MISCELLANEOUS.cpp  ../../../Sources/GPIO.cpp  ../../../Sources/DHT.cpp DHT11_1.1.cpp -lpthread -o DHT11_1.1.out
echo "Finished"
